name: Reusable Deploy
on: 
  workflow_call: # Allows this workflow to be called from other workflow
    inputs:
      artifact-name:
        description: The name of the deployable artifact file
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: Result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code Binaries
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output info
        run: echo "Deploying..."
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT